name: Build Universal APK

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore and Set up Signing Environment
      env:
        RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
      run: |
        echo "Decoding Keystore..."
        KEYSTORE_FILE_PATH="${{ runner.temp }}/release.jks" # Store in a temporary, job-specific directory
        echo "$RELEASE_KEYSTORE_BASE64" | base64 --decode > "$KEYSTORE_FILE_PATH"
        echo "Keystore decoded to $KEYSTORE_FILE_PATH"

        echo "Setting environment variables for Gradle signing..."
        echo "RELEASE_STORE_FILE_PATH=$KEYSTORE_FILE_PATH" >> $GITHUB_ENV
        echo "RELEASE_KEYSTORE_PASSWORD=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
        echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> $GITHUB_ENV
        echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> $GITHUB_ENV
        echo "Signing environment variables set."

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk # Adjust path if your APK is in a different location
