name: Build and Release Universal APK

on:
  push:
    tags:
      - 'v*' # Trigger only on version tags (e.g., v1.0.0)

jobs:
  build:
    name: Build Universal APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # Use Zulu as the JDK distribution
        java-version: '17' # Android requires Java 17 in modern builds

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33 # Change to the target SDK version of your app
        build-tools: '33.0.0'
        ndk: false

    - name: Build Universal APK
      run: ./gradlew assembleRelease

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false